// GENERATED by tools/gen-text.js from text/menu.txt -- edit that and re-run, not this.
(define TEXT_MENU            10)
(define TXT_MENU_HELP_TURN   0)
(define TXT_MENU_HELP_ENDING 1)
(define TXT_MENU_HELP_OFFICE 2)
(define TXT_MENU_HELP_TYPING 3)
(define TXT_MENU_HELP_KEYS   4)
